[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
api = { path = "../api" }

tracing = {workspace = true}
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
tonic = { workspace = true }
