[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = {workspace = true}
tonic = {workspace = true}

[build-dependencies]
tonic-build = {workspace = true}
protoc-bin-vendored = {workspace = true}
