[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {workspace = true}
prost = {workspace = true}
tonic = {workspace = true}

[build-dependencies]
tonic-build = {workspace = true}
